const MAX_QUEUES = 128;
const MAX_SUP_PORTS = 1;

const MBUF_CACHE_SIZE = 128;
const MBUF_DATA_SIZE = 2048 + 128;

const BURST_TX_DRAIN_US = 100;
const BURST_RX_WAIT_US = 15;
const BURST_RX_RETRIES = 4;

const JUMBO_FRAME_MAX_SIZE = 0x2600;

const DEVICE_MAC_LEARNING = 0;
const DEVICE_RX = 1;
const DEVICE_SAFE_REMOVE = 2;

const RTE_TEST_RX_DESC_DEFAULT = 1024;
const RTE_TEST_TX_DESC_DEFAULT = 512;

const INVALID_PORT_ID = 0xFF;
const MAX_LONG_OPT_SZ = 64;
